spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false

  jwt:
    secretKey: ${JWT_SECRET}
    header: ${HEADER}
    prefix: ${PREFIX}
    accessExp: ${ACCESS_EXP}
    refreshExp: ${REFRESH_EXP}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

cloud:
  aws:
    bucket: ${BUCKET_NAME}
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    stack:
      auto: false

user:
  profile:
    default-image-url: ${DEFAULT_PROFILE_IMAGE}